version: "3"
services:
  tailscale:
    image: beardedtek-com/tailscale:dev
    container_name: tailscale
    restart: unless-stopped
    privileged: true
    volumes:
      - ./varlib:/var/lib
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    environment:
      TAILSCALE_AUTHKEY: ${TAILSCALE_AUTHKEY}
      TAILSCALE_HOSTNAME: ${TAILSCALE_HOSTNAME}
      TAILSCALE_TAGS: ${TAILSCALE_TAGS}
      TAILSCALE_ADVERTISE_ROUTE: ${TAILSCALE_ADVERTISE_ROUTE}
      TAILSCALE_ENABLE: ${TAILSCALE_ENABLE:-true}
